#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
umask 077
UNILARK_REPO=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
UNILARK_CONFIG=${1:-"$HOME/.unilark/agy.toml"}
UNILARK_DATA_DIR=${UNILARK_DATA_DIR:-"$HOME/.unilark"}
ENV_FILE="$UNILARK_DATA_DIR/lark.env"
if [[ -L "$UNILARK_DATA_DIR" || -L "$ENV_FILE" ]]; then
  warn "数据目录和凭据文件不能是符号链接。"; exit 1
fi
mkdir -p -- "$UNILARK_DATA_DIR"
chmod 700 -- "$UNILARK_DATA_DIR"
if [[ ! -x "$UNILARK_REPO/.venv/bin/unilark" || ! -f "$UNILARK_CONFIG" ]]; then
  warn "需要已有 .venv 和 AGY 实例配置。用法：$0 /绝对路径/unilark.toml"; exit 1
fi
[[ -t 0 ]] || { warn "请在本机交互终端运行，不能通过管道输入。"; exit 1; }

banner "Unilark：连接自己的 Lark / 飞书机器人"

stage "选择应用区域"
say "顺序：选择区域 → 创建机器人并保存凭据 → 权限 → 长连接/发布/配对 → 验证。"
say "edition 和 App ID 保存到本机 lark.env；App Secret 隐藏输入，同文件仅本人可读。"
open_url "https://open.larksuite.com/app"
say "飞书中国版控制台：https://open.feishu.cn/app"
while true; do
  ask UNILARK_LARK_EDITION "输入 lark（国际版）或 feishu（中国版）："
  [[ "$UNILARK_LARK_EDITION" == lark || "$UNILARK_LARK_EDITION" == feishu ]] && break
done
write_env UNILARK_LARK_EDITION "$UNILARK_LARK_EDITION"
if [[ "$UNILARK_LARK_EDITION" == lark ]]; then
  UNILARK_CONSOLE=https://open.larksuite.com/app
else
  UNILARK_CONSOLE=https://open.feishu.cn/app
fi

stage "创建本机专用机器人并保存凭据"
open_url "$UNILARK_CONSOLE"
step "创建企业自建应用（或选已有的本机专用应用），在应用能力中启用机器人。"
step "进入应用的凭证与基础信息页面，复制 App ID 和 App Secret。不同语言标签可能略有差异。"
while true; do
  ask UNILARK_LARK_APP_ID "粘贴 App ID："
  [[ "$UNILARK_LARK_APP_ID" =~ ^cli_[A-Za-z0-9_]+$ ]] && break
done
while true; do
  ask_secret UNILARK_LARK_APP_SECRET "粘贴 App Secret（隐藏输入，不要发到聊天里）："
  [[ -n "$UNILARK_LARK_APP_SECRET" ]] && break
done
write_env UNILARK_LARK_APP_ID "$UNILARK_LARK_APP_ID"
write_env UNILARK_LARK_APP_SECRET "$UNILARK_LARK_APP_SECRET"
chmod 600 -- "$ENV_FILE"
unset UNILARK_LARK_APP_SECRET

stage "开通消息权限"
open_url "$UNILARK_CONSOLE/$UNILARK_LARK_APP_ID"
step "在权限管理中查找并开通：im:message、im:message:send_as_bot。"
step "接收私聊消息还需要 im:message.p2p_msg:readonly；按平台展示的依赖一起申请。"
say "只做私聊、普通消息卡片；无需群消息、通讯录、文件读写或 CardKit 流式权限。"
say "权限是否真正生效，要由后面的真实收发确认。"
pause "权限已添加后按 Enter："

stage "长连接、发布与本机身份确认"
open_url "$UNILARK_CONSOLE/$UNILARK_LARK_APP_ID"
step "在事件与回调中选择长连接，订阅 im.message.receive_v1 和 card.action.trigger。"
step "若页面要求先建立连接，下面 pair 命令启动后再回控制台保存。"
step "在版本管理与发布中创建版本；可用范围只包含本人，然后按租户要求发布/安装。"
step "稍后在机器人私聊发送终端显示的 /pair 配对码；回来核对身份，并粘贴自己的 open_id。"
say "知道配对码的人无法直接启动任务，必须在这个本机终端确认。"
say "配对窗口 5 分钟。若配置/审批耗时更久，可重跑向导；已保存字段会保留。"
pause "准备好在浏览器和终端之间切换后，按 Enter 启动长连接和配对："
"$UNILARK_REPO/.venv/bin/unilark" --credentials "$ENV_FILE" \
  --state "$UNILARK_DATA_DIR/state.db" pair

stage "配置完成，开始真实接力验证"
say "工具风险判断由 AGY 自身审批设置决定。会话内容会经过 Lark 和所选模型通道。"
say "本向导只完成配置和配对；还没有验证端到端接力。"
say "接下来启动网关（持续运行，Ctrl-C 退出，AGY 桌面与会话会保留）："
printf '  %q --config %q --credentials %q --state %q run\n' \
  "$UNILARK_REPO/.venv/bin/unilark" "$UNILARK_CONFIG" "$ENV_FILE" "$UNILARK_DATA_DIR/state.db"
say "在机器人私聊发 /new，再发一条只要求文本回复的测试消息。"
say "然后在 AGY 桌面打开同一原生会话，确认来源、双端后续输入与回复，再测试停止和审批。"
say "完整清单：repo/docs/LARK-SETUP.md。跑完向导后告诉协作助手：应用已配置、owner 已配对。"
pause "已记录下一步后按 Enter："
finish
say "配置已保存；真实 Lark ↔ AGY 接力仍待验收。"
